CREATE TABLE CATEGORIA(
    ID NUMBER(5),
    NOME VARCHAR2(100)
);

CREATE TABLE TAREFA(
    ID NUMBER(5),
    TITULO VARCHAR2(100),
    DESCRICAO VARCHAR2(400),
    CATEGORIA_ID NUMBER(5),      
    DATA_CRIACAO DATE,           
    TEMPO_ESTIMADO_MIN NUMBER(4), 
    STATUS VARCHAR2(20)
);

ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_ID_PK 
PRIMARY KEY (ID);

ALTER TABLE TAREFA ADD CONSTRAINT TAREFA_ID_PK 
PRIMARY KEY (ID);

ALTER TABLE TAREFA ADD CONSTRAINT TAREFA_CATEGORIA_ID_FK
FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID);

SET SERVEROUTPUT ON;
DECLARE
    v_ID NUMBER(5) := 1;
BEGIN
    dbms_output.put_line(v_ID);
    v_ID := 2;
    dbms_output.put_line(v_ID);
END;


DECLARE
    v_ID NUMBER(5) := 1;
    v_NOME VARCHAR2(100) := 'ESTUDO';
BEGIN
    INSERT INTO CATEGORIA (ID, NOME) VALUES (v_ID, v_NOME);
    COMMIT;
END;

DECLARE
    v_ID CATEGORIA.ID%type := 2;
    v_NOME CATEGORIA.NOME%type := 'GERAL';
BEGIN
    INSERT INTO CATEGORIA (ID, NOME) VALUES (v_ID, v_NOME);
    COMMIT;
END;

DECLARE
    v_REGISTRO_CATEGORIA CATEGORIA%ROWTYPE;
BEGIN
    v_REGISTRO_CATEGORIA.ID := 3;
    v_REGISTRO_CATEGORIA.NOME := 'TRABALHO';

    INSERT INTO CATEGORIA VALUES v_REGISTRO_CATEGORIA;
    COMMIT;
END;

DECLARE
    v_ID CATEGORIA.ID%type := 4;
    v_NOME CATEGORIA.NOME%type := 'Familia';
BEGIN
    INSERT INTO CATEGORIA (ID, NOME) VALUES (v_ID, UPPER(v_NOME));
    COMMIT;
END;

DECLARE
    v_ID NUMBER(5) := 1;
    v_NOME VARCHAR2(100) := 'estudo concurso';
BEGIN
    UPDATE CATEGORIA SET NOME = UPPER(v_NOME) WHERE ID = v_ID;
    COMMIT;
END;

DECLARE
    v_ID CATEGORIA.ID%type := 4;
BEGIN
    DELETE FROM CATEGORIA WHERE ID = v_ID;
    COMMIT;
END;


SELECT * FROM CATEGORIA;

DROP PROCEDURE incluir_categoria;

CREATE PROCEDURE incluir_categoria
(p_ID IN NUMBER, p_NOME IN VARCHAR2)
IS
BEGIN
    INSERT INTO CATEGORIA (ID, NOME) VALUES (p_ID, UPPER(p_NOME));
    COMMIT;
END;

EXECUTE incluir_categoria(4, 'família');

CREATE OR REPLACE PROCEDURE incluir_categoria
(p_ID IN CATEGORIA.ID%type, p_NOME IN CATEGORIA.NOME%type)
IS
BEGIN
    INSERT INTO CATEGORIA (ID, NOME) VALUES (p_ID, UPPER(p_NOME));
    COMMIT;
END;

EXECUTE incluir_categoria(5, 'igreja');

SET SERVEROUTPUT ON;
DECLARE
    v_ID CATEGORIA.ID%type := 1;
    v_IDSaida CATEGORIA.ID%type;
    v_NOME CATEGORIA.NOME%type;
BEGIN
    SELECT NOME INTO v_NOME FROM CATEGORIA WHERE ID = v_ID;
    SELECT ID INTO v_IDSaida FROM CATEGORIA WHERE ID= v_ID;
    dbms_output.put_line(v_NOME);
    dbms_output.put_line(v_IDSaida);
END;

SET SERVEROUTPUT ON;
DECLARE
    v_ID CATEGORIA.ID%type := 1;
    v_IDSaida CATEGORIA.ID%type;
    v_NOME CATEGORIA.NOME%type;
BEGIN
    SELECT ID, NOME INTO v_IDSaida, v_NOME
    FROM CATEGORIA WHERE ID = v_ID;
    dbms_output.put_line('ID RETORNADO: ' || v_NOME);
    dbms_output.put_line('NOME RETORNADO: ' || v_IDSaida);
END;

CREATE OR REPLACE FUNCTION obter_nome_categoria
(p_ID IN CATEGORIA.ID%type)
RETURN CATEGORIA.NOME%type
IS
    v_NOME CATEGORIA.NOME%type;
BEGIN
    SELECT NOME INTO v_NOME FROM CATEGORIA WHERE ID = p_ID;
    RETURN v_NOME;
END;

SELECT ID, obter_nome_categoria(ID), NOME, LOWER(NOME) FROM CATEGORIA;

CREATE OR REPLACE PROCEDURE incluir_tarefa
(
    p_ID TAREFA.ID%type,
    p_TITULO TAREFA.TITULO%type,
    p_DESCRICAO TAREFA.DESCRICAO%type,
    p_CATEGORIA TAREFA.CATEGORIA_ID%type,
    p_CRIACAO TAREFA.DATA_CRIACAO%type,
    p_TEMPO_ESTIMADO_MIN TAREFA.TEMPO_ESTIMADO_MIN%type,
    p_STATUS TAREFA.STATUS%type
)
IS
BEGIN 
    INSERT INTO TAREFA
    VALUES
    (p_ID, p_TITULO, p_DESCRICAO, p_CATEGORIA, p_CRIACAO, p_TEMPO_ESTIMADO_MIN,p_STATUS);
    COMMIT;
END;


EXECUTE incluir_tarefa(1, 'Programação', 'Estudar Spring Boot - Rest API', 1,TO_DATE('2026-07-14', 'YYYY-MM-DD'), 60, 'Pendente');

SELECT * FROM TAREFA;

SET SERVEROUTPUT ON;
DECLARE
    v_TEMPO TAREFA.TEMPO_ESTIMADO_MIN%type := 5;
    v_COMPLEXIDADE VARCHAR2(20);
BEGIN
    IF v_TEMPO <= 15 THEN
        v_COMPLEXIDADE := 'RÁPIDA';
    ELSIF v_TEMPO <= 60 THEN
        v_COMPLEXIDADE := 'MÉDIA';
    ELSIF v_TEMPO <= 120 THEN
        v_COMPLEXIDADE := 'LONGA';
    ELSE
        v_COMPLEXIDADE := 'COMPLEXA';
    END IF;

    DBMS_OUTPUT.PUT_LINE('O status estimado da tarefa é: '|| v_COMPLEXIDADE);
END;

ALTER TABLE TAREFA ADD COMPLEXIDADE VARCHAR2(20);


CREATE OR REPLACE FUNCTION complexidade_tarefa
    (p_TEMPO IN TAREFA.TEMPO_ESTIMADO_MIN%type)
    RETURN TAREFA.COMPLEXIDADE%type
IS
    v_COMPLEXIDADE TAREFA.COMPLEXIDADE%type;
BEGIN 
    IF p_TEMPO <= 15 THEN
        v_COMPLEXIDADE := 'RÁPIDA';
    ELSIF p_TEMPO <= 60 THEN
        v_COMPLEXIDADE := 'MÉDIA';
    ELSIF p_TEMPO <= 120 THEN
        v_COMPLEXIDADE := 'LONGA';
    ELSE
        v_COMPLEXIDADE := 'COMPLEXA';
    END IF;
    RETURN v_COMPLEXIDADE;
END;

SELECT TEMPO_ESTIMADO_MIN, complexidade_tarefa(TEMPO_ESTIMADO_MIN) FROM TAREFA;

CREATE OR REPLACE PROCEDURE incluir_tarefa
(
    p_ID TAREFA.ID%type,
    p_TITULO TAREFA.TITULO%type,
    p_DESCRICAO TAREFA.DESCRICAO%type,
    p_CATEGORIA TAREFA.CATEGORIA_ID%type,
    p_TEMPO_ESTIMADO_MIN TAREFA.TEMPO_ESTIMADO_MIN%type,
    p_STATUS TAREFA.STATUS%type
)
IS
    v_COMPLEXIDADE TAREFA.COMPLEXIDADE%type;
BEGIN
    v_COMPLEXIDADE := complexidade_tarefa(p_TEMPO_ESTIMADO_MIN);

    INSERT INTO TAREFA
    VALUES
    (p_ID, p_TITULO, p_DESCRICAO, p_CATEGORIA, SYSDATE, p_TEMPO_ESTIMADO_MIN, p_STATUS, v_COMPLEXIDADE);
END;

EXECUTE incluir_tarefa(3,'Organização Pessoal', 'Lavar as roupas',2,50,'Pendente');













