CREATE TABLE CATEGORIA(
    ID NUMBER(5),
    NOME VARCHAR2(100)
);

CREATE TABLE TAREFA(
    ID NUMBER(5),
    TITULO VARCHAR2(100),
    DESCRICAO VARCHAR2(400),
    CATEGORIA_ID NUMBER(5),      
    DATA_CRIACAO DATE,           
    TEMPO_ESTIMADO_MIN NUMBER(4), 
    STATUS VARCHAR2(20)
);

ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_ID_PK 
PRIMARY KEY (ID);

ALTER TABLE TAREFA ADD CONSTRAINT TAREFA_ID_PK 
PRIMARY KEY (ID);

ALTER TABLE TAREFA ADD CONSTRAINT TAREFA_CATEGORIA_ID_FK
FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID);